CREATE DATABASE IF NOT EXISTS `hvdb`;
CREATE DATABASE IF NOT EXISTS `hapi`;
CREATE DATABASE IF NOT EXISTS `test_hvdb`;
CREATE DATABASE IF NOT EXISTS `test_hapi`;
CREATE DATABASE IF NOT EXISTS `test_ubersmith`;
